beepboop9000/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from beepboop9000.views import HomePageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path('', include('register.urls')),
    path('', include('report.urls')),
    path('', include('view.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

view/urls.py
from django.urls import path
from .views import view_view

urlpatterns = [
  # path('view', SearchView.as_view(), name='view'),
  path('view', view_view, name='view'),
]

register/models.py
from django.db import models

from django.conf import settings

class Organisation(models.Model):
    def __str__(self):
        return self.name

    COUNTRY_CHOICES = [
        ('great_britain','Great Britain'),
        ('ireland', 'Ireland'),
    ]
    TYPE_CHOICES = [
        ('pubbar', 'Pub/Bar'),
        ('club', 'Nightclub'),
        ('society', 'University Society'),
        ('school', 'School'),
        ('office', 'Office'),
        ('store', 'Store'),
        ('other', 'Other'),
    ]
    CITY_CHOICES = [
        ('edinburgh', 'Edinburgh'),
        ('dublin', 'Dublin'),
    ]
    name = models.CharField(max_length=150)
    country = models.CharField(max_length=50, choices=COUNTRY_CHOICES)
    city = models.CharField(max_length=50, choices=CITY_CHOICES)
    type = models.CharField(max_length=25, choices=TYPE_CHOICES)
    email = models.EmailField()
    report_count = models.IntegerField(blank=False, null=False, default=0)

    # to prevent spam - allows admin to manually allow an orgnaisation to show
    # verified = models.BooleanField(default=False)

    class Meta:
        # sort results by name by default when querying DB
        ordering = ['name']

view/templates/view/view.html
{% extends "beepboop9000/base.html" %}
{% load static %}

{% block title %}View{% endblock %}

{% block content %}

<div class="container-fluid">

  <div class="row justify-content-center">
    <div class="col-sm-12 text-center mb-2">
      <h1>View organisations</h1>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col">
      <form class="d-flex" action="{% url 'view' %}">
        <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>

  <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-4 g-4">
  {% for organisation in orgs %}
  <div class="col">
    <div class="card h-100">
      <!-- <img src="..." class="card-img-top" alt="..."> -->
      <div class="card-body">
        <h4 class="card-title">{{ organisation.name }}</h4>
        <h6 class="card-text text-muted">{{ organisation.get_type_display }}</h6>
        <p class="card-text">{{ organisation.get_city_display }}, {{ organisation.get_country_display }}</p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <span style="float: left;">No. incidents reported:</span>
          <span style="float: right;">{{ organisation.report_count }}</span>
        </li>
      </ul>
    </div>
  </div>
  {% endfor %}
  </div>
</div>

{% endblock %}